### PR TITLE
Mirror from OCM around 56

### PR DESCRIPTION
**Pull request by JustinKuli**
Closes https://github.com/stolostron/governance-policy-framework-addon/issues/79

### CODE REVIEW

**Comment by dhaiducek** [comment]
That's a lot of vulnerabilities. If the error assignments are set to an empty assignment, maybe that'll make gosec (and the linter happy)? Alternatively, does the function need to return an error?

**Comment by JustinKuli** [comment]
There are a small number of cases where the error is useful, so I'd rather not fully remove it. Slightly disappointing that the linter comments aren't read by `gosec`...

**Comment by JustinKuli** [comment]
Now it's failed twice with
```
• [FAILED] [185.881 seconds]
Test Gatekeeper ConstraintTemplate and constraint sync [skip-minimum]
/home/runner/work/governance-policy-framework-addon/governance-policy-framework-addon/governance-policy-framework-addon/test/e2e/case17_gatekeeper_sync_test.go:26
  [It] should return Gatekeeper audit results
  /home/runner/work/governance-policy-framework-addon/governance-policy-framework-addon/governance-policy-framework-addon/test/e2e/case17_gatekeeper_sync_test.go:230

  Begin Captured GinkgoWriter Output >>
    STEP: Checking if policy status is compliant for the constraint 04/18/23 19:25:44.25
    STEP: Adding ConfigMaps that violate the constraint 04/18/23 19:25:44.257
    STEP: Checking if policy status is noncompliant for the constraint 04/18/23 19:25:44.274
    STEP: Deleting the namespace case17-gk-test 04/18/23 19:28:44.275
    STEP: Deleting policy case17-gk-policy on the hub in ns:managed 04/18/23 19:28:44.279
    STEP: Cleaning up the events for the policy case17-gk-policy 04/18/23 19:28:44.291
    STEP: Deleting policy case17-gk-policy-2 on the hub in ns:managed 04/18/23 19:28:44.916
    STEP: Cleaning up the events for the policy case17-gk-policy-2 04/18/23 19:28:44.923
    STEP: Fixing the Gatekeeper webhook if required 04/18/23 19:28:45.101
    STEP: Waiting for the namespace case17-gk-test to be deleted 04/18/23 19:28:45.112
  << End Captured GinkgoWriter Output

  Timed out after 180.001s.
  Expected success, but got an error:
      <*errors.errorString | 0xc0003fbf90>: {
          s: "Assertion in callback at /home/runner/work/governance-policy-framework-addon/governance-policy-framework-addon/governance-policy-framework-addon/test/e2e/case17_gatekeeper_sync_test.go:306 failed:\nExpected\n    <string>: NonCompliant; NonCompliant; template-error; Mapping not found, check if the required ConstraintTemplate has been deployed: the resource version was not found: constraints.gatekeeper.sh/v1beta1, Kind=Case17ConstraintTemplate\nnot to equal\n    <string>: NonCompliant; NonCompliant; template-error; Mapping not found, check if the required ConstraintTemplate has been deployed: the resource version was not found: constraints.gatekeeper.sh/v1beta1, Kind=Case17ConstraintTemplate",
      }
      Assertion in callback at /home/runner/work/governance-policy-framework-addon/governance-policy-framework-addon/governance-policy-framework-addon/test/e2e/case17_gatekeeper_sync_test.go:306 failed:
      Expected
          <string>: NonCompliant; NonCompliant; template-error; Mapping not found, check if the required ConstraintTemplate has been deployed: the resource version was not found: constraints.gatekeeper.sh/v1beta1, Kind=Case17ConstraintTemplate
      not to equal
          <string>: NonCompliant; NonCompliant; template-error; Mapping not found, check if the required ConstraintTemplate has been deployed: the resource version was not found: constraints.gatekeeper.sh/v1beta1, Kind=Case17ConstraintTemplate
  In [It] at: /home/runner/work/governance-policy-framework-addon/governance-policy-framework-addon/governance-policy-framework-addon/test/e2e/case17_gatekeeper_sync_test.go:308
```

**Comment by JustinKuli** [comment]
Quantum test: when I'm debugging it (including locally), it passes.

**Review by dhaiducek — APPROVED** [review]
Thanks for the update! Having `make gosec-scan` in the workflow twice gives me pause, but it won't hurt and we can clean it up in a separate PR.

**Pull request merged**
