### PR TITLE
Manual sync of upstream PRs: #126, #127

### LINKED ISSUE #326: 😿 Failed to sync the upstream PRs: #125, #126, #127
🪞 Magic Mirror 🪞 failed to sync the following upstream pull-requests because one or more patches couldn't cleanly apply:
* open-cluster-management-io/governance-policy-framework-addon#125
* open-cluster-management-io/governance-policy-framework-addon#126
* open-cluster-management-io/governance-policy-framework-addon#127

Syncing is paused for the branch main on stolostron/governance-policy-framework-addon until the issue is manually resolved and this issue is closed.

Syncing error:
```
Error: To https://github.com/stolostron/governance-policy-framework-addon.git
!	HEAD:refs/heads/magic-mirror-main-1711050546722	[remote rejected] (refusing to allow a GitHub App to create or update workflow `.github/workflows/framework-kind.yml` without `workflows` permission)
Done
Pushing to https://github.com/stolostron/governance-policy-framework-addon.git
POST git-receive-pack (7081 bytes)
error: failed to push some refs to 'https://github.com/stolostron/governance-policy-framework-addon.git'

```

Commands to recreate the issue:

```
git cherry-pick -x e5b17fcb79faeb56ba5b379a9eecd98f280b643f~2..e5b17fcb79faeb56ba5b379a9eecd98f280b643f --allow-empty --keep-redundant-commits
git cherry-pick -x 5aae21cb520b22398a3a67abc0a134eae425c334~3..5aae21cb520b22398a3a67abc0a134eae425c334 --allow-empty --keep-redundant-commits
git cherry-pick -x 6a8baf33b678533fb6ebe268edd47a421cc81143~1..6a8baf33b678533fb6ebe268edd47a421cc81143 --allow-empty --keep-redundant-commits
```

sad Yoda

### PR DESCRIPTION
**Pull request by mprahl**
Closes #326 

I skipped this PR:
https://github.com/open-cluster-management-io/governance-policy-framework-addon/pull/125

Let me know if some of it should have been pulled in @zyjjay.

### CODE REVIEW

**Comment by zyjjay** [comment]
@mprahl Skipping that PR should be ok!

**Review by JustinKuli — APPROVED** [review]

**Pull request merged**
