### PR TITLE
[2.8 Manual Sync] Reduce memory utilization of caching events

### PR DESCRIPTION
**Pull request by mprahl**
Addresses https://issues.redhat.com/browse/ACM-6783

This removes all unnecessary fields in an Event object before it is cached. Additionally, a field selector is added to avoid caching events unrelated to policy compliance.

Relates:
https://issues.redhat.com/browse/ACM-6063

Signed-off-by: mprahl <mprahl@users.noreply.github.com>
(cherry picked from commit c59e473d3473baa558ee0d3774e271a1bdd369d6)

### CODE REVIEW

**Comment by mprahl** [comment]
/override "KinD / Tests (latest, false, hosted)"

**Review by JustinKuli — APPROVED** [review]

**Comment by mprahl** [comment]
@JustinKuli I just rebased the PR hoping that the hosted mode CI would pass.

**Comment by mprahl** [comment]
/override "KinD / Tests (latest, false, hosted)"

**Comment by mprahl** [comment]
@JustinKuli and @dhaiducek could you please review?

**Review by JustinKuli — APPROVED** [review]

**Pull request merged**
